version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webserver
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - "./main-challenge/app:/app"
    environment:
      - PAYMENT_SERVICE_HOST=payment-app
      
      # Pass only the minimum required variables for the fallback method
      - CODESPACE_NAME=${CODESPACE_NAME}
      - GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN=${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}

  payment-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paymentserver
    ports:
      - "8001:8001"
    networks:
      - app-network
    volumes:
      - "./payment/:/app"
    environment:
      # Pass the minimum required variables here as well
      - CODESPACE_NAME=${CODESPACE_NAME}
      - GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN=${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}

networks:
  app-network:
    driver: bridge